---
- name: Install Apache on backend servers
  yum:
    name: httpd
    state: present

- name: Start and enable Apache service
  service:
    name: httpd
    state: started
    enabled: true

- name: Deploy backend index page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Apache

